### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by pdailey** [tinkerspy/Automaton-Machine-Editor#1]
The machine editor website seems to be down. I tried to run the php scripts on my computer, but am a complete noob. Any idea when the site will be back up?

Thanks!

**Comment by tinkerspy** [comment]
Thanks for the warning. The editor is on my home server and my ISP occasionally changes my IP address. I changed the DNS records so you should be able to connect whenever your DNS cache expires. On Windows you could run `ipconfig /flushdns` to speed things up.

**Comment by pdailey** [comment]
Thanks again, this is an incredible library you've written.

---

Peter Dailey

**Comment by tinkerspy** [comment]
Thanks!

**Comment by bryan-arcus** [comment]
@tinkerspy Looks like it's gone down again.
Edit: It's back up now. Thanks!

**Comment by tinkerspy** [comment]
Oh yes. I'm away for the holidays and I figured it was a good idea to reset the router VM and then I accidentally turned it off. 

I went back yesterday night and turned it on again for you guys ;-)
