### ISSUE TITLE
Private variables not maintained after editing in machine editor

### ISSUE THREAD

**Issue by EclipseBoom** [tinkerspy/Automaton-Machine-Editor#3]
After adding private variables to the Atm_my_machine.h file in the IDE, they are not maintained when the machine files are loaded into the machine editor, edited and then resaved.

Changes to method prototypes and method code appear to be maintained.

**Comment by EclipseBoom** [comment]
Sorry.  It looks like it is working correctly.  I must have been saving the template rather than the modified code.  I just checked again and the variables were maintained.

**Comment by tinkerspy** [comment]
I know it's not very reliable. In the backend it uses git to merge the new code with the existing. But git isn't exactly full proof.

Personally I often copy/paste the relevant sections myself ;-)
